Shape Population Viewer: ShapePopulationViewer Class Reference
ShapePopulationViewer Class Reference
The ShapePopulationViewer class.
#include <ShapePopulationViewer.h>
Public Slots
virtual void slotExit ()
ShapePopulationViewer::slotExit.
Public Member Functions
ShapePopulationViewer ()
ShapePopulationViewer::ShapePopulationViewer.
~ShapePopulationViewer ()
Protected Slots
void on_checkBox_9_toggled (bool checked)
ShapePopulationViewer::on_checkBox_9_toggled.
void flipMeshes ()
ShapePopulationViewer::flipMeshes.
void writeMeshes ()
ShapePopulationViewer::writeMeshes.
void openVTKS ()
ShapePopulationViewer::openVTKS.
void on_checkBox_10_toggled (bool checked)
ShapePopulationViewer::on_checkBox_10_toggled.
void on_lineEdit_editingFinished ()
ShapePopulationViewer::on_lineEdit_editingFinished.
void on_checkBox_3_toggled (bool checked)
ShapePopulationViewer::on_checkBox_3_toggled.
void on_comboBox_currentIndexChanged (const QString &arg1)
ShapePopulationViewer::on_comboBox_currentIndexChanged.
void on_toolButton_clicked ()
ShapePopulationViewer::on_toolButton_clicked.
void on_toolButton_2_clicked ()
ShapePopulationViewer::on_toolButton_clicked.
void on_toolButton_3_clicked ()
ShapePopulationViewer::on_toolButton_clicked.
void on_toolButton_4_clicked ()
ShapePopulationViewer::on_toolButton_clicked.
void on_toolButton_5_clicked ()
ShapePopulationViewer::on_toolButton_clicked.
void on_toolButton_6_clicked ()
ShapePopulationViewer::on_toolButton_clicked.
void viewChange (int x, int y, int z)
ShapePopulationViewer::viewChange.
Protected Member Functions
void ModifiedHandler ()
ShapePopulationViewer::ModifiedHandler.
void resizeEvent (QResizeEvent *event)
ShapePopulationViewer::resizeEvent.
void updateWidgets ()
ShapePopulationViewer::updateWidgets.
void updateCMaps ()
ShapePopulationViewer::updateCMaps.
Protected Attributes
bool synced
QDir directory
QVector< QVTKWidget * > * widgetList
QVector< vtkPolyData * > * polyList
QVector< vtkPolyDataMapper * > * mapperList
QVector< QString > * colorMaps
QSize scrollAreaSize
QString cmap
double * coords
double distance
int prevCols
int prevRows
int phi
double PI
int loaded
int sequence
Additional Inherited Members
Public Attributes inherited from Ui_ShapePopulationViewer
QAction * actionOpenFile
QAction * actionExit
QAction * actionPrint
QAction * actionHelp
QAction * actionSave
QAction * actionFlip_Meshes
QAction * actionWrite_Back_Meshes
QAction * actionOpen_vtk_Files
QWidget * centralwidget
QGridLayout * gridLayout
QGroupBox * groupBox_6
QGroupBox * groupBox_4
QWidget * verticalLayoutWidget
QVBoxLayout * verticalLayout
QComboBox * comboBox
QGroupBox * groupBox_5
QWidget * verticalLayoutWidget_3
QVBoxLayout * verticalLayout_2
QCheckBox * checkBox_9
QHBoxLayout * horizontalLayout_7
QCheckBox * checkBox_10
QLineEdit * lineEdit
QLabel * label_5
QCheckBox * checkBox_3
QGroupBox * groupBox
QGridLayout * gridLayout_3
QWidget * widget
QToolButton * toolButton
QToolButton * toolButton_2
QToolButton * toolButton_4
QToolButton * toolButton_3
QToolButton * toolButton_5
QToolButton * toolButton_6
ViewportWidget * dockWidget
QWidget * dockWidgetContents
QGridLayout * gridLayout_2
QScrollArea * scrollArea
QWidget * scrollAreaWidgetContents
QGridLayout * gridLayout_5
QMenuBar * menuBar
QMenu * menuTools
QMenu * menuFile
Detailed Description
The ShapePopulationViewer class.
ShapePopulationViewer Gui class specification. This class contains all model data and controller callbacks, if we are going to consider the code within the MVC paradigm. See ui_ShapePopulationViewer.h for information on the construction of the gui itself. That is an autogenerated file from the ShapePopulationViewer.ui file, which could also be used as reference.
Author
Michael Guarino
Constructor & Destructor Documentation
ShapePopulationViewer::ShapePopulationViewer ()
ShapePopulationViewer::ShapePopulationViewer.
Constructor for ShapePopulationViewer GUI, it will initialize model vectors, connect some callbacks and also draw the arrow icons.
Author
Michael Guarino
References Ui_ShapePopulationViewer::actionExit, Ui_ShapePopulationViewer::actionFlip_Meshes, Ui_ShapePopulationViewer::actionOpen_vtk_Files, Ui_ShapePopulationViewer::actionWrite_Back_Meshes, colorMaps, flipMeshes(), loaded, mapperList, openVTKS(), phi, PI, polyList, Ui_ShapePopulationViewer::setupUi(), slotExit(), synced, Ui_ShapePopulationViewer::toolButton, Ui_ShapePopulationViewer::toolButton_2, Ui_ShapePopulationViewer::toolButton_3, Ui_ShapePopulationViewer::toolButton_4, Ui_ShapePopulationViewer::toolButton_5, Ui_ShapePopulationViewer::toolButton_6, widgetList, and writeMeshes().
ShapePopulationViewer::~ShapePopulationViewer () inline
Member Function Documentation
void ShapePopulationViewer::flipMeshes () protected slot
ShapePopulationViewer::flipMeshes.
Callback for the flip meshes menu item, this function remaps the scalars in the specified meshes to simulate a polar shift in the parameterization. No remapping of the pointdata individuals is performed, though.
Author
Michael Guarino
References ModifiedHandler(), and polyList.
Referenced by ShapePopulationViewer().
void ShapePopulationViewer::ModifiedHandler () protected
ShapePopulationViewer::ModifiedHandler.
Handler to any modified event sent by a QVTKWidget in the viewport. The handler calls render on all the windows provided user is viewing in synchronized mode.
Author
Michael Guarino
References synced, and widgetList.
Referenced by flipMeshes(), on_comboBox_currentIndexChanged(), updateWidgets(), and viewChange().
void ShapePopulationViewer::on_checkBox_10_toggled (bool checked) protected slot
ShapePopulationViewer::on_checkBox_10_toggled.
Callback for the View in ___ columns checkbox. This reads from the ___ columns line edit, and then re-arranges the QVTKWidgets according to the integer entry. Returns if an integer is not entered (or if the same integer was reentered or if there are no widgets to rearrange).
Parameters
checked
Author
Michael Guarino
References Ui_ShapePopulationViewer::checkBox_9, Ui_ShapePopulationViewer::lineEdit, prevCols, prevRows, Ui_ShapePopulationViewer::scrollAreaWidgetContents, and widgetList.
Referenced by on_lineEdit_editingFinished().
void ShapePopulationViewer::on_checkBox_3_toggled (bool checked) protected slot
ShapePopulationViewer::on_checkBox_3_toggled.
Callback to the Desynchronize Meshes checkbox. Sets the synced instance variable.
Parameters
checked
Author
Michael Guarino
References synced.
void ShapePopulationViewer::on_checkBox_9_toggled (bool checked) protected slot
ShapePopulationViewer::on_checkBox_9_toggled.
Callback for the View All Meshes checkbox.
Parameters
checked
Author
Michael Guarino
References Ui_ShapePopulationViewer::checkBox_10, Ui_ShapePopulationViewer::scrollArea, scrollAreaSize, and Ui_ShapePopulationViewer::scrollAreaWidgetContents.
void ShapePopulationViewer::on_comboBox_currentIndexChanged (const QString & arg1) protected slot
ShapePopulationViewer::on_comboBox_currentIndexChanged.
Callback to the colormap dropdown menu. This will pull the selected text from the menu, call the updateCMaps() helper, then call Render on all the QVTKWidgets to render the updates.
Parameters
arg1
Author
Michael Guarino
References cmap, Ui_ShapePopulationViewer::comboBox, ModifiedHandler(), synced, and updateCMaps().
void ShapePopulationViewer::on_lineEdit_editingFinished () protected slot
ShapePopulationViewer::on_lineEdit_editingFinished.
Callback to the ___ columns line edit. This checks if the view in ___ columns checkbox is selected, then it will simply call its callback with true passed as the check state. So a lineedit modification also activates column rearrangement.
Author
Michael Guarino
References Ui_ShapePopulationViewer::checkBox_10, and on_checkBox_10_toggled().
void ShapePopulationViewer::on_toolButton_2_clicked () protected slot
ShapePopulationViewer::on_toolButton_clicked.
Callback to the -Z axis view button. See viewChange() for implemntation details.
Author
Joe Waggoner
References viewChange().
void ShapePopulationViewer::on_toolButton_3_clicked () protected slot
ShapePopulationViewer::on_toolButton_clicked.
Callback to the +X axis view button. See viewChange() for implemntation details.
Author
Joe Waggoner
References viewChange().
void ShapePopulationViewer::on_toolButton_4_clicked () protected slot
ShapePopulationViewer::on_toolButton_clicked.
Callback to the -X axis view button. See viewChange() for implemntation details.
Author
Joe Waggoner
References viewChange().
void ShapePopulationViewer::on_toolButton_5_clicked () protected slot
ShapePopulationViewer::on_toolButton_clicked.
Callback to the +Y axis view button. See viewChange() for implemntation details.
Author
Joe Waggoner
References viewChange().
void ShapePopulationViewer::on_toolButton_6_clicked () protected slot
ShapePopulationViewer::on_toolButton_clicked.
Callback to the -Y axis view button. See viewChange() for implemntation details.
Author
Joe Waggoner
References viewChange().
void ShapePopulationViewer::on_toolButton_clicked () protected slot
ShapePopulationViewer::on_toolButton_clicked.
Callback to the +Z axis view button. See viewChange() for implemntation details.
Author
Joe Waggoner
References viewChange().
void ShapePopulationViewer::openVTKS () protected slot
ShapePopulationViewer::openVTKS.
Callback to Open .vtk Files menu item, this simply clears all current widgets, pulls open a filedialog to let the user select a directory and then calls the updateWidgets() helper function
Author
Michael Guarino
References directory, loaded, Ui_ShapePopulationViewer::scrollAreaWidgetContents, updateWidgets(), and widgetList.
Referenced by ShapePopulationViewer().
void ShapePopulationViewer::resizeEvent (QResizeEvent * event) protected
ShapePopulationViewer::resizeEvent.
Overrides QMainWindow's resize event to also help resize the contents of the dockwidget's scrollarea. There is no other easy way to do this with the Qt tools as they are currently.
Parameters
event - variable containing the event data for a resize (needed for a super call)
Author
Michael Guarino
References Ui_ShapePopulationViewer::dockWidget, Ui_ShapePopulationViewer::scrollArea, Ui_ShapePopulationViewer::scrollAreaWidgetContents, and ViewportWidget::size().
void ShapePopulationViewer::slotExit () virtual slot
ShapePopulationViewer::slotExit.
Close function for the gui.
Referenced by ShapePopulationViewer().
void ShapePopulationViewer::updateCMaps () protected
ShapePopulationViewer::updateCMaps.
Helper function which sets the working color map to the one saved in the cmap QString instance variable
Author
Michael Guarino
References cmap, mapperList, phi, and polyList.
Referenced by on_comboBox_currentIndexChanged().
void ShapePopulationViewer::updateWidgets () protected
ShapePopulationViewer::updateWidgets.
Helper function which reads a directory filled with .vtk files and renders each polydata within in a separate QVTKWidget. All model vectors are filled as well.
Author
Michael Guarino
References colorMaps, Ui_ShapePopulationViewer::comboBox, directory, Ui_ShapePopulationViewer::lineEdit, mapperList, ModifiedHandler(), phi, polyList, prevCols, prevRows, Ui_ShapePopulationViewer::scrollAreaWidgetContents, and widgetList.
Referenced by openVTKS().
void ShapePopulationViewer::viewChange (int x, int y, int z) protected slot
ShapePopulationViewer::viewChange.
Helper function for viewing the meshes along a specified axis. Parameters (1,0,0) will allow you to view the mesh from the end of the positive x-axis, for instance. Generally, <x,y,z> is a distance-normalized vector specifying the position you want to place the viewing camera (distance being the current distance from the camera to the mesh).
Parameters
x
y
z
Author
Joe Waggoner
References coords, distance, loaded, ModifiedHandler(), synced, and widgetList.
Referenced by on_toolButton_2_clicked(), on_toolButton_3_clicked(), on_toolButton_4_clicked(), on_toolButton_5_clicked(), on_toolButton_6_clicked(), and on_toolButton_clicked().
void ShapePopulationViewer::writeMeshes () protected slot
ShapePopulationViewer::writeMeshes.
Callback to the Write Meshes menu item, this will write every current polydata back to their original files. The choice of saving each file individually with a user specified file name was eliminated as it is entirely possible that very large numbers of meshes are going to be visualized, make that procedure tedious.
Author
Michael Guarino
References directory, and polyList.
Referenced by ShapePopulationViewer().
Member Data Documentation
QString ShapePopulationViewer::cmap protected
Referenced by on_comboBox_currentIndexChanged(), and updateCMaps().
QVector<QString>* ShapePopulationViewer::colorMaps protected
Referenced by ShapePopulationViewer(), and updateWidgets().
double* ShapePopulationViewer::coords protected
Referenced by viewChange().
QDir ShapePopulationViewer::directory protected
Referenced by openVTKS(), updateWidgets(), and writeMeshes().
double ShapePopulationViewer::distance protected
Referenced by viewChange().
int ShapePopulationViewer::loaded protected
Referenced by openVTKS(), ShapePopulationViewer(), and viewChange().
QVector<vtkPolyDataMapper *>* ShapePopulationViewer::mapperList protected
Referenced by ShapePopulationViewer(), updateCMaps(), and updateWidgets().
int ShapePopulationViewer::phi protected
Referenced by ShapePopulationViewer(), updateCMaps(), and updateWidgets().
double ShapePopulationViewer::PI protected
Referenced by ShapePopulationViewer().
QVector<vtkPolyData *>* ShapePopulationViewer::polyList protected
Referenced by flipMeshes(), ShapePopulationViewer(), updateCMaps(), updateWidgets(), and writeMeshes().
int ShapePopulationViewer::prevCols protected
Referenced by on_checkBox_10_toggled(), and updateWidgets().
int ShapePopulationViewer::prevRows protected
Referenced by on_checkBox_10_toggled(), and updateWidgets().
QSize ShapePopulationViewer::scrollAreaSize protected
Referenced by on_checkBox_9_toggled().
int ShapePopulationViewer::sequence protected
bool ShapePopulationViewer::synced protected
Referenced by ModifiedHandler(), on_checkBox_3_toggled(), on_comboBox_currentIndexChanged(), ShapePopulationViewer(), and viewChange().
QVector<QVTKWidget *>* ShapePopulationViewer::widgetList protected
Referenced by ModifiedHandler(), on_checkBox_10_toggled(), openVTKS(), ShapePopulationViewer(), updateWidgets(), and viewChange().
The documentation for this class was generated from the following files:
ShapePopulationViewer.h
ShapePopulationViewer.cxx