Shape Population Viewer: ViewportWidget Class Reference
ViewportWidget Class Reference
The ViewportWidget class.
#include <ViewportWidget.h>
Public Member Functions
ViewportWidget (QWidget *parent, QWidget *areaConts)
ViewportWidget.
QSize size ()
size
Protected Member Functions
void resizeEvent (QResizeEvent *event)
resizeEvent
Detailed Description
The ViewportWidget class.
Extension of the QDockWidget class to handle resizing of children of children of the widget effectively. Basically everything about QDockWidget remains unchanged except it's resizeEvent function is overridden. A constructor and instance variable is added to faciliate.
Constructor & Destructor Documentation
ViewportWidget::ViewportWidget (QWidget * parent, QWidget * areaConts) inline
ViewportWidget.
Additional constructor, calls superconstructor and initializes an instance variable (in our case the contents of the scroll area whose parent is the dock widget).
Parameters
parent
areaConts
Member Function Documentation
void ViewportWidget::resizeEvent (QResizeEvent * event) inline protected
resizeEvent
Overriden resizeEvent handler. Basically, make the super call, then make a standardized resize to the instance variable. (In our case this is the contents of the scroll area whose parent is the dock widget).
Parameters
event
References size().
QSize ViewportWidget::size () inline
size
Clarity function returning the size of the dock widget.
Returns
Referenced by resizeEvent(), and ShapePopulationViewer::resizeEvent().
The documentation for this class was generated from the following file:
ViewportWidget.h